a = 
  veryLongLongLongName veryLongLongLongArg veryLongLongLongArg veryLongLongLongArg

a = 
  veryLongLongLongName veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg

a = 
  veryLongLongLongName veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg

a = 
  veryLongLongLongName veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg

a = 
  veryLongLongLongName veryLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg
                       veryLongLongLongArg

tests = 
  hello [name "space space space space space space space space space space space" thing
        ,name "space space space space space space space space space space space" thing
        ,name "space space space space space space space space space space space" thing]

tests = 
  hello goodbye
        [name "space space space space space space space space space space space" thing
        ,name "space space space space space space space space space space space" thing
        ,name "space space space space space space space space space space space" thing]
