unless hello $
  case thing of
    Left a  -> 3
    Right b -> 5

when hello $
  case thing of
    Left a  -> 3
    Right b -> 5

a = \line -> case a of
  Left a  -> a
  Right b -> b

map (\x -> x) [1, 2, 3]

forM_ lst $ \x -> do
  putStrLn x

forM_ lst $ \x -> putStrLn x

Value <$> thing <*> secondThing

Value <$> thing
      <*> secondThing
      <*> thirdThing
      <*> fourthThing
      <*> Just thisissolong
      <*> Just stilllonger

f e = 5
  where
    a = b

a = b
  where
    c = d
    e = f

a = b
  where
    c = d

    e = f
