a = veryLongLongLongName veryLongLongLongArg veryLongLongLongArg veryLongLongLongArg

a = veryLongLongLongName veryLongLongLongArg veryLongLongLongArg veryLongLongLongArg
      veryLongLongLongArg

a = veryLongLongLongName veryLongLongLongArg veryLongLongLongArg veryLongLongLongArg
      veryLongLongLongArg veryLongLongLongArg

a = veryLongLongLongName veryLongLongLongArg veryLongLongLongArg veryLongLongLongArg
      veryLongLongLongArg veryLongLongLongArg veryLongLongLongArg

a = veryLongLongLongName
      veryLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongArg
      veryLongLongLongArg
      veryLongLongLongArg
      veryLongLongLongArg
      veryLongLongLongArg
      veryLongLongLongArg
