instance A B
>
-- Comment

instance A B
>
>
-- Comment

data ConvertSpec f =
       ConvertSpec
         { convertToIpynb :: f Bool
         , convertInput :: f FilePath
         , convertOutput :: f FilePath
         , convertLhsStyle :: f (LhsStyle T.Text)
         , convertOverwriteFiles :: Bool
         }

f b
  | b = 3

f b
  | b =
      3

a =
  case x of
    Record { x = x }
      | test -> ans

a =
  case x of
    Just x 
      | test -> ans

{-# NOINLINE val #-}

{-# INLINE val #-}
