a = case f x of
  1 -> 1
  2 -> 3
  3 -> 4
  _ -> 100

a = case f x of
  1 -> 1
  2 -> 3
  3 -> 4
  _ -> 100

a = case f x of
  1 -> 1
  2 -> 3
  3 -> 4
  _ -> 100

a = case f x of
  Nothing -> 1
  Just x  -> 3

a = case f x of
  Nothing -> 1
  Just x  -> 3

a = case f x of
  Nothing -> 1
  Just x  -> 3

a = case f x of
  Nothing -> do
    return 3
  Just x -> return ()

a = case f x of
  Nothing -> do
    return 3
  Just x -> do
    return 5
